version: '3.8'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.prod
    volumes:
      - ./api:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    restart: unless-stopped
    env_file:
      - ./.env.prod
    command: node dist/app.js
    container_name: "express-ts-api-prod"

